### ISSUE TITLE
PolyBlocker can’t be activated in Blender 4.0 on an M1 Mac

### ISSUE THREAD

**Issue by hannesdelbeke** [DanielBoxer/polyblocker#1]
PolyBlocker can’t be activated in 4.0 on an M1 Mac

reported by Reg_Nullify in [this post](https://blenderartists.org/t/rabbit-hole-of-free-add-ons/1446091/22)

![image](https://github.com/DanielBoxer/polyblocker/assets/3758308/0f3e87af-5f84-4824-9116-5df067daebc1)

## workaround
someone posted a workaround for now:

As a workaround you can fix the code manually.
Go into the addon folder, open line_draw.py

On the first lines (8 and 9) change
```python
SHADER_2D = gpu.shader.from_builtin(“2D_UNIFORM_COLOR”)
SHADER_3D = gpu.shader.from_builtin(“3D_UNIFORM_COLOR”)
```
for
```python
SHADER_2D = gpu.shader.from_builtin(“UNIFORM_COLOR”)
SHADER_3D = gpu.shader.from_builtin(“UNIFORM_COLOR”)
```
save it, re open blender and it should work

**Comment by danielboxer** [comment]
Thanks for letting me know and for the details!
